"""fase_2_mermas

Revision ID: 339cc6405003
Revises: c8e29904253c
Create Date: 2026-08-07 18:22:06.889759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '339cc6405003'
down_revision: Union[str, Sequence[str], None] = 'c8e29904253c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_sucursal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('stock_actual', sa.Float(), nullable=False),
    sa.Column('stock_minimo', sa.Float(), nullable=False),
    sa.Column('stock_maximo', sa.Float(), nullable=True),
    sa.Column('ultima_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes_stock.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'sucursal_id', 'ingrediente_id', name='uq_empresa_sucursal_ingrediente')
    )
    op.create_index(op.f('ix_stock_sucursal_empresa_id'), 'stock_sucursal', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_stock_sucursal_id'), 'stock_sucursal', ['id'], unique=False)
    op.create_index(op.f('ix_stock_sucursal_ingrediente_id'), 'stock_sucursal', ['ingrediente_id'], unique=False)
    op.create_index(op.f('ix_stock_sucursal_sucursal_id'), 'stock_sucursal', ['sucursal_id'], unique=False)
    op.add_column('registro_mermas', sa.Column('sucursal_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_registro_mermas_sucursal_id'), 'registro_mermas', ['sucursal_id'], unique=False)
    op.create_foreign_key(None, 'registro_mermas', 'sucursales', ['sucursal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registro_mermas', type_='foreignkey')
    op.drop_index(op.f('ix_registro_mermas_sucursal_id'), table_name='registro_mermas')
    op.drop_column('registro_mermas', 'sucursal_id')
    op.drop_index(op.f('ix_stock_sucursal_sucursal_id'), table_name='stock_sucursal')
    op.drop_index(op.f('ix_stock_sucursal_ingrediente_id'), table_name='stock_sucursal')
    op.drop_index(op.f('ix_stock_sucursal_id'), table_name='stock_sucursal')
    op.drop_index(op.f('ix_stock_sucursal_empresa_id'), table_name='stock_sucursal')
    op.drop_table('stock_sucursal')
    # ### end Alembic commands ###
