"""fase_3_inventario

Revision ID: 4da61f207883
Revises: 339cc6405003
Create Date: 2026-08-07 22:31:40.370246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4da61f207883'
down_revision: Union[str, Sequence[str], None] = '339cc6405003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plantillas_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_plantillas_inventario_empresa_id'), 'plantillas_inventario', ['empresa_id'], unique=False)
    
    op.create_table('conteos_fisicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plantilla_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('Borrador', 'En_Conteo', 'Revision', 'Cerrado', name='estado_conteo'), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['plantilla_id'], ['plantillas_inventario.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conteos_fisicos_empresa_id'), 'conteos_fisicos', ['empresa_id'], unique=False)
    
    op.create_table('items_conteo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conteo_id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('stock_teorico_sistema', sa.Float(), nullable=False),
    sa.Column('stock_real_contado', sa.Float(), nullable=False),
    sa.Column('diferencia_calculada', sa.Float(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conteo_id'], ['conteos_fisicos.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes_stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_conteo_empresa_id'), 'items_conteo', ['empresa_id'], unique=False)
    
    op.create_table('ajustes_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conteo_id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('stock_anterior', sa.Float(), nullable=False),
    sa.Column('stock_nuevo', sa.Float(), nullable=False),
    sa.Column('motivo', sa.String(length=200), nullable=False),
    sa.Column('valor_ajuste', sa.Float(), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=False),
    sa.Column('fecha_ajuste', sa.DateTime(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conteo_id'], ['conteos_fisicos.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes_stock.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ajustes_inventario_empresa_id'), 'ajustes_inventario', ['empresa_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ajustes_inventario_empresa_id'), table_name='ajustes_inventario')
    op.drop_table('ajustes_inventario')
    op.drop_index(op.f('ix_items_conteo_empresa_id'), table_name='items_conteo')
    op.drop_table('items_conteo')
    op.drop_index(op.f('ix_conteos_fisicos_empresa_id'), table_name='conteos_fisicos')
    op.drop_table('conteos_fisicos')
    op.drop_index(op.f('ix_plantillas_inventario_empresa_id'), table_name='plantillas_inventario')
    op.drop_table('plantillas_inventario')
    # ### end Alembic commands ###
