"""Migracion inicial a Postgres

Revision ID: 503d5a1c2297
Revises: 
Create Date: 2026-08-06 02:00:16.291601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '503d5a1c2297'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('higiene_personal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleado_nombre', sa.String(length=100), nullable=False),
    sa.Column('empleado_cargo', sa.String(length=50), nullable=True),
    sa.Column('fecha_auditoria', sa.Date(), nullable=False),
    sa.Column('hora_auditoria', sa.Time(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('auditor_nombre', sa.String(length=100), nullable=False),
    sa.Column('auditor_firma', sa.Text(), nullable=True),
    sa.Column('uñas_cortas_limpias', sa.Boolean(), nullable=True),
    sa.Column('manos_limpias', sa.Boolean(), nullable=True),
    sa.Column('sin_joyas', sa.Boolean(), nullable=True),
    sa.Column('uniforme_limpio', sa.Boolean(), nullable=True),
    sa.Column('cabello_cubierto', sa.Boolean(), nullable=True),
    sa.Column('calzado_adecuado', sa.Boolean(), nullable=True),
    sa.Column('sin_lesiones_visibles', sa.Boolean(), nullable=True),
    sa.Column('lavado_manos_correcto', sa.Boolean(), nullable=True),
    sa.Column('aprobado', sa.Boolean(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('foto_evidencia', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_higiene_personal_empleado_nombre'), 'higiene_personal', ['empleado_nombre'], unique=False)
    op.create_index(op.f('ix_higiene_personal_fecha_auditoria'), 'higiene_personal', ['fecha_auditoria'], unique=False)
    op.create_index(op.f('ix_higiene_personal_id'), 'higiene_personal', ['id'], unique=False)
    op.create_table('ingredientes_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.Enum('CARNES', 'VERDURAS', 'FRUTAS', 'LACTEOS', 'GRANOS', 'CONDIMENTOS', 'BEBIDAS', 'OTROS', name='categoriaingrediente'), nullable=False),
    sa.Column('unidad_medida', sa.Enum('KG', 'G', 'L', 'ML', 'UNIDAD', 'CAJA', 'BOLSA', name='unidadmedida'), nullable=False),
    sa.Column('stock_actual', sa.Float(), nullable=False),
    sa.Column('stock_minimo', sa.Float(), nullable=False),
    sa.Column('stock_maximo', sa.Float(), nullable=True),
    sa.Column('costo_unitario', sa.Float(), nullable=False),
    sa.Column('costo_promedio', sa.Float(), nullable=False),
    sa.Column('dias_alerta_vencimiento', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredientes_stock_id'), 'ingredientes_stock', ['id'], unique=False)
    op.create_index(op.f('ix_ingredientes_stock_nombre'), 'ingredientes_stock', ['nombre'], unique=False)
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('contacto', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proveedores_id'), 'proveedores', ['id'], unique=False)
    op.create_index(op.f('ix_proveedores_nombre'), 'proveedores', ['nombre'], unique=False)
    op.create_table('registro_temperaturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_nombre', sa.String(length=100), nullable=False),
    sa.Column('equipo_ubicacion', sa.String(length=100), nullable=True),
    sa.Column('temperatura', sa.Float(), nullable=False),
    sa.Column('temperatura_objetivo_min', sa.Float(), nullable=False),
    sa.Column('temperatura_objetivo_max', sa.Float(), nullable=False),
    sa.Column('fecha_medicion', sa.Date(), nullable=False),
    sa.Column('hora_medicion', sa.Time(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('responsable', sa.String(length=100), nullable=False),
    sa.Column('responsable_firma', sa.Text(), nullable=True),
    sa.Column('dentro_rango', sa.Boolean(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('foto_evidencia', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registro_temperaturas_equipo_nombre'), 'registro_temperaturas', ['equipo_nombre'], unique=False)
    op.create_index(op.f('ix_registro_temperaturas_fecha_medicion'), 'registro_temperaturas', ['fecha_medicion'], unique=False)
    op.create_index(op.f('ix_registro_temperaturas_fecha_registro'), 'registro_temperaturas', ['fecha_registro'], unique=False)
    op.create_index(op.f('ix_registro_temperaturas_id'), 'registro_temperaturas', ['id'], unique=False)
    op.create_table('sucursales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sucursales_activa'), 'sucursales', ['activa'], unique=False)
    op.create_index(op.f('ix_sucursales_id'), 'sucursales', ['id'], unique=False)
    op.create_index(op.f('ix_sucursales_nombre'), 'sucursales', ['nombre'], unique=True)
    op.create_table('requerimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto', sa.String(length=200), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_estimado', sa.Float(), nullable=False),
    sa.Column('prioridad', sa.Enum('ALTA', 'MEDIA', 'BAJA', name='prioridad'), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requerimientos_id'), 'requerimientos', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('ADMINISTRADOR', 'ENCARGADO', 'OPERADOR', name='rolusuario'), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_activo'), 'usuarios', ['activo'], unique=False)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_nombre_completo'), 'usuarios', ['nombre_completo'], unique=False)
    op.create_index(op.f('ix_usuarios_rol'), 'usuarios', ['rol'], unique=False)
    op.create_index(op.f('ix_usuarios_sucursal_id'), 'usuarios', ['sucursal_id'], unique=False)
    op.create_table('control_gastos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('SERVICIOS', 'INSUMOS_NO_ALIMENTICIOS', 'TRANSPORTE', 'MANTENIMIENTO', 'OTROS', name='tipogasto'), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha_gasto', sa.Date(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('proveedor', sa.String(length=200), nullable=True),
    sa.Column('numero_comprobante', sa.String(length=50), nullable=True),
    sa.Column('foto_comprobante', sa.String(length=500), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'APROBADO', 'RECHAZADO', name='estadoaprobacion'), nullable=True),
    sa.Column('responsable_usuario_id', sa.Integer(), nullable=True),
    sa.Column('aprobado_por_usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['aprobado_por_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['responsable_usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_gastos_id'), 'control_gastos', ['id'], unique=False)
    op.create_index(op.f('ix_control_gastos_responsable_usuario_id'), 'control_gastos', ['responsable_usuario_id'], unique=False)
    op.create_table('lista_verificacion_diario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('APERTURA', 'CIERRE', name='tipochecklist'), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_registro', sa.Time(), nullable=False),
    sa.Column('fecha_hora_completa', sa.DateTime(), nullable=True),
    sa.Column('responsable_usuario_id', sa.Integer(), nullable=False),
    sa.Column('responsable_firma', sa.Text(), nullable=True),
    sa.Column('cocina_limpia', sa.Boolean(), nullable=True),
    sa.Column('cocina_ordenada', sa.Boolean(), nullable=True),
    sa.Column('basureros_vacios', sa.Boolean(), nullable=True),
    sa.Column('equipos_funcionando', sa.Boolean(), nullable=True),
    sa.Column('temperaturas_ok', sa.Boolean(), nullable=True),
    sa.Column('extintores_ok', sa.Boolean(), nullable=True),
    sa.Column('uniformes_limpios', sa.Boolean(), nullable=True),
    sa.Column('manos_lavadas', sa.Boolean(), nullable=True),
    sa.Column('cabello_cubierto', sa.Boolean(), nullable=True),
    sa.Column('almacen_ordenado', sa.Boolean(), nullable=True),
    sa.Column('sin_plagas', sa.Boolean(), nullable=True),
    sa.Column('fecha_vencimiento_revisada', sa.Boolean(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('foto_evidencia', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['responsable_usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lista_verificacion_diario_fecha'), 'lista_verificacion_diario', ['fecha'], unique=False)
    op.create_index(op.f('ix_lista_verificacion_diario_fecha_hora_completa'), 'lista_verificacion_diario', ['fecha_hora_completa'], unique=False)
    op.create_index(op.f('ix_lista_verificacion_diario_id'), 'lista_verificacion_diario', ['id'], unique=False)
    op.create_index(op.f('ix_lista_verificacion_diario_responsable_usuario_id'), 'lista_verificacion_diario', ['responsable_usuario_id'], unique=False)
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Enum('TAREA', 'ALERTA', 'MERMA_PENDIENTE', 'INCIDENCIA', name='tiponotificacion'), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_lectura', sa.DateTime(), nullable=True),
    sa.Column('entidad_relacionada', sa.String(length=50), nullable=True),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificaciones_fecha_creacion'), 'notificaciones', ['fecha_creacion'], unique=False)
    op.create_index(op.f('ix_notificaciones_id'), 'notificaciones', ['id'], unique=False)
    op.create_index(op.f('ix_notificaciones_leida'), 'notificaciones', ['leida'], unique=False)
    op.create_index(op.f('ix_notificaciones_tipo'), 'notificaciones', ['tipo'], unique=False)
    op.create_index(op.f('ix_notificaciones_usuario_id'), 'notificaciones', ['usuario_id'], unique=False)
    op.create_table('registro_compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_factura', sa.String(length=50), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('fecha_compra', sa.Date(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('iva', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('foto_recibo', sa.String(length=500), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'APROBADO', 'RECHAZADO', name='estadoaprobacion'), nullable=True),
    sa.Column('creado_por_usuario_id', sa.Integer(), nullable=True),
    sa.Column('aprobado_por_usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aprobado_por_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['creado_por_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registro_compras_id'), 'registro_compras', ['id'], unique=False)
    op.create_index(op.f('ix_registro_compras_numero_factura'), 'registro_compras', ['numero_factura'], unique=True)
    op.create_table('registro_mermas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('VENCIMIENTO', 'DAÑO', 'DERRAME', 'ROBO', 'OTRO', name='tipomerma'), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('valor_perdida', sa.Float(), nullable=False),
    sa.Column('fecha_merma', sa.Date(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('responsable_usuario_id', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('foto_evidencia', sa.String(length=500), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'APROBADO', 'RECHAZADO', name='estadoaprobacion'), nullable=True),
    sa.Column('aprobado_por_usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aprobado_por_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes_stock.id'], ),
    sa.ForeignKeyConstraint(['responsable_usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registro_mermas_id'), 'registro_mermas', ['id'], unique=False)
    op.create_index(op.f('ix_registro_mermas_responsable_usuario_id'), 'registro_mermas', ['responsable_usuario_id'], unique=False)
    op.create_table('detalle_compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('costo_unitario', sa.Float(), nullable=False),
    sa.Column('costo_total', sa.Float(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('lote', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['compra_id'], ['registro_compras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes_stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalle_compras_id'), 'detalle_compras', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalle_compras_id'), table_name='detalle_compras')
    op.drop_table('detalle_compras')
    op.drop_index(op.f('ix_registro_mermas_responsable_usuario_id'), table_name='registro_mermas')
    op.drop_index(op.f('ix_registro_mermas_id'), table_name='registro_mermas')
    op.drop_table('registro_mermas')
    op.drop_index(op.f('ix_registro_compras_numero_factura'), table_name='registro_compras')
    op.drop_index(op.f('ix_registro_compras_id'), table_name='registro_compras')
    op.drop_table('registro_compras')
    op.drop_index(op.f('ix_notificaciones_usuario_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_tipo'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_leida'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_fecha_creacion'), table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_index(op.f('ix_lista_verificacion_diario_responsable_usuario_id'), table_name='lista_verificacion_diario')
    op.drop_index(op.f('ix_lista_verificacion_diario_id'), table_name='lista_verificacion_diario')
    op.drop_index(op.f('ix_lista_verificacion_diario_fecha_hora_completa'), table_name='lista_verificacion_diario')
    op.drop_index(op.f('ix_lista_verificacion_diario_fecha'), table_name='lista_verificacion_diario')
    op.drop_table('lista_verificacion_diario')
    op.drop_index(op.f('ix_control_gastos_responsable_usuario_id'), table_name='control_gastos')
    op.drop_index(op.f('ix_control_gastos_id'), table_name='control_gastos')
    op.drop_table('control_gastos')
    op.drop_index(op.f('ix_usuarios_sucursal_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_rol'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_nombre_completo'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_activo'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_requerimientos_id'), table_name='requerimientos')
    op.drop_table('requerimientos')
    op.drop_index(op.f('ix_sucursales_nombre'), table_name='sucursales')
    op.drop_index(op.f('ix_sucursales_id'), table_name='sucursales')
    op.drop_index(op.f('ix_sucursales_activa'), table_name='sucursales')
    op.drop_table('sucursales')
    op.drop_index(op.f('ix_registro_temperaturas_id'), table_name='registro_temperaturas')
    op.drop_index(op.f('ix_registro_temperaturas_fecha_registro'), table_name='registro_temperaturas')
    op.drop_index(op.f('ix_registro_temperaturas_fecha_medicion'), table_name='registro_temperaturas')
    op.drop_index(op.f('ix_registro_temperaturas_equipo_nombre'), table_name='registro_temperaturas')
    op.drop_table('registro_temperaturas')
    op.drop_index(op.f('ix_proveedores_nombre'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_id'), table_name='proveedores')
    op.drop_table('proveedores')
    op.drop_index(op.f('ix_ingredientes_stock_nombre'), table_name='ingredientes_stock')
    op.drop_index(op.f('ix_ingredientes_stock_id'), table_name='ingredientes_stock')
    op.drop_table('ingredientes_stock')
    op.drop_index(op.f('ix_higiene_personal_id'), table_name='higiene_personal')
    op.drop_index(op.f('ix_higiene_personal_fecha_auditoria'), table_name='higiene_personal')
    op.drop_index(op.f('ix_higiene_personal_empleado_nombre'), table_name='higiene_personal')
    op.drop_table('higiene_personal')
    # ### end Alembic commands ###
