"""Branding y SuperAdmin

Revision ID: 8031e44472c9
Revises: 225d1158bcb6
Create Date: 2026-08-06 03:44:51.052459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8031e44472c9'
down_revision: Union[str, Sequence[str], None] = '225d1158bcb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('nombre_comercial', sa.String(length=200), nullable=True))
    op.add_column('empresas', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('empresas', sa.Column('color_primario', sa.String(length=7), nullable=True))
    op.add_column('empresas', sa.Column('color_secundario', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'color_secundario')
    op.drop_column('empresas', 'color_primario')
    op.drop_column('empresas', 'logo_url')
    op.drop_column('empresas', 'nombre_comercial')
    # ### end Alembic commands ###
