"""fase_4_master_plan

Revision ID: c8e29904253c
Revises: 9b80c4d8f1a3
Create Date: 2026-08-07 02:40:36.103113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8e29904253c'
down_revision: Union[str, Sequence[str], None] = '9b80c4d8f1a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('duracion_minutos', sa.Integer(), nullable=True),
    sa.Column('url_contenido', sa.String(length=500), nullable=True),
    sa.Column('obligatorio', sa.Boolean(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cursos_empresa_id'), 'cursos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_cursos_id'), 'cursos', ['id'], unique=False)
    op.create_table('alertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('AVISO', 'ALERTA', 'URGENTE', name='tipoalerta'), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVA', 'RECONOCIDA', 'RESUELTA', name='estadoalerta'), nullable=False),
    sa.Column('entidad_tipo', sa.String(length=50), nullable=True),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('usuario_creador_id', sa.Integer(), nullable=True),
    sa.Column('usuario_asignado_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_resuelta', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_asignado_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_creador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertas_empresa_id'), 'alertas', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_alertas_estado'), 'alertas', ['estado'], unique=False)
    op.create_index(op.f('ix_alertas_id'), 'alertas', ['id'], unique=False)
    op.create_index(op.f('ix_alertas_tipo'), 'alertas', ['tipo'], unique=False)
    op.create_table('capacitaciones_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'EN_PROGRESO', 'COMPLETADO', 'VENCIDO', name='estadocapacitacion'), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_completado', sa.DateTime(), nullable=True),
    sa.Column('puntuacion', sa.Float(), nullable=True),
    sa.Column('certificado_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capacitaciones_usuarios_curso_id'), 'capacitaciones_usuarios', ['curso_id'], unique=False)
    op.create_index(op.f('ix_capacitaciones_usuarios_empresa_id'), 'capacitaciones_usuarios', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_capacitaciones_usuarios_estado'), 'capacitaciones_usuarios', ['estado'], unique=False)
    op.create_index(op.f('ix_capacitaciones_usuarios_id'), 'capacitaciones_usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_capacitaciones_usuarios_usuario_id'), 'capacitaciones_usuarios', ['usuario_id'], unique=False)
    op.create_table('evidencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entidad_tipo', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=False),
    sa.Column('url_foto', sa.String(length=500), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidencias_empresa_id'), 'evidencias', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_evidencias_entidad_id'), 'evidencias', ['entidad_id'], unique=False)
    op.create_index(op.f('ix_evidencias_entidad_tipo'), 'evidencias', ['entidad_tipo'], unique=False)
    op.create_index(op.f('ix_evidencias_id'), 'evidencias', ['id'], unique=False)
    op.create_index(op.f('ix_evidencias_usuario_id'), 'evidencias', ['usuario_id'], unique=False)
    op.create_table('incidencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('EQUIPO', 'HIGIENE', 'TEMPERATURA', 'SEGURIDAD', 'OTRO', name='tipoincidencia'), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('ABIERTA', 'EN_REVISION', 'RESUELTA', 'CERRADA', name='estadoincidencia'), nullable=False),
    sa.Column('severidad', sa.Enum('BAJA', 'MEDIA', 'ALTA', 'CRITICA', name='severidad'), nullable=False),
    sa.Column('reportado_por_id', sa.Integer(), nullable=False),
    sa.Column('asignado_a_id', sa.Integer(), nullable=True),
    sa.Column('fecha_reporte', sa.DateTime(), nullable=True),
    sa.Column('fecha_resolucion', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asignado_a_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['reportado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidencias_empresa_id'), 'incidencias', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_incidencias_estado'), 'incidencias', ['estado'], unique=False)
    op.create_index(op.f('ix_incidencias_id'), 'incidencias', ['id'], unique=False)
    op.create_index(op.f('ix_incidencias_reportado_por_id'), 'incidencias', ['reportado_por_id'], unique=False)
    op.create_index(op.f('ix_incidencias_tipo'), 'incidencias', ['tipo'], unique=False)
    op.create_table('ejecuciones_checklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_ejecucion', sa.Date(), nullable=False),
    sa.Column('hora_ejecucion', sa.Time(), nullable=False),
    sa.Column('estado', sa.Enum('COMPLETADA', 'PENDIENTE', 'NO_CONFORME', name='estadoejecucion'), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('firma', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['lista_verificacion_diario.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ejecuciones_checklist_checklist_id'), 'ejecuciones_checklist', ['checklist_id'], unique=False)
    op.create_index(op.f('ix_ejecuciones_checklist_empresa_id'), 'ejecuciones_checklist', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_ejecuciones_checklist_estado'), 'ejecuciones_checklist', ['estado'], unique=False)
    op.create_index(op.f('ix_ejecuciones_checklist_fecha_ejecucion'), 'ejecuciones_checklist', ['fecha_ejecucion'], unique=False)
    op.create_index(op.f('ix_ejecuciones_checklist_id'), 'ejecuciones_checklist', ['id'], unique=False)
    op.create_index(op.f('ix_ejecuciones_checklist_usuario_id'), 'ejecuciones_checklist', ['usuario_id'], unique=False)
    op.add_column('empresas', sa.Column('tema', sa.String(length=20), nullable=True))
    op.execute("UPDATE empresas SET tema = 'claro' WHERE tema IS NULL")
    op.alter_column('empresas', 'tema', nullable=False, server_default=sa.text("'claro'"))
    op.add_column('empresas', sa.Column('favicon_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'favicon_url')
    op.drop_column('empresas', 'tema')
    op.drop_index(op.f('ix_ejecuciones_checklist_usuario_id'), table_name='ejecuciones_checklist')
    op.drop_index(op.f('ix_ejecuciones_checklist_id'), table_name='ejecuciones_checklist')
    op.drop_index(op.f('ix_ejecuciones_checklist_fecha_ejecucion'), table_name='ejecuciones_checklist')
    op.drop_index(op.f('ix_ejecuciones_checklist_estado'), table_name='ejecuciones_checklist')
    op.drop_index(op.f('ix_ejecuciones_checklist_empresa_id'), table_name='ejecuciones_checklist')
    op.drop_index(op.f('ix_ejecuciones_checklist_checklist_id'), table_name='ejecuciones_checklist')
    op.drop_table('ejecuciones_checklist')
    op.drop_index(op.f('ix_incidencias_tipo'), table_name='incidencias')
    op.drop_index(op.f('ix_incidencias_reportado_por_id'), table_name='incidencias')
    op.drop_index(op.f('ix_incidencias_id'), table_name='incidencias')
    op.drop_index(op.f('ix_incidencias_estado'), table_name='incidencias')
    op.drop_index(op.f('ix_incidencias_empresa_id'), table_name='incidencias')
    op.drop_table('incidencias')
    op.drop_index(op.f('ix_evidencias_usuario_id'), table_name='evidencias')
    op.drop_index(op.f('ix_evidencias_id'), table_name='evidencias')
    op.drop_index(op.f('ix_evidencias_entidad_tipo'), table_name='evidencias')
    op.drop_index(op.f('ix_evidencias_entidad_id'), table_name='evidencias')
    op.drop_index(op.f('ix_evidencias_empresa_id'), table_name='evidencias')
    op.drop_table('evidencias')
    op.drop_index(op.f('ix_capacitaciones_usuarios_usuario_id'), table_name='capacitaciones_usuarios')
    op.drop_index(op.f('ix_capacitaciones_usuarios_id'), table_name='capacitaciones_usuarios')
    op.drop_index(op.f('ix_capacitaciones_usuarios_estado'), table_name='capacitaciones_usuarios')
    op.drop_index(op.f('ix_capacitaciones_usuarios_empresa_id'), table_name='capacitaciones_usuarios')
    op.drop_index(op.f('ix_capacitaciones_usuarios_curso_id'), table_name='capacitaciones_usuarios')
    op.drop_table('capacitaciones_usuarios')
    op.drop_index(op.f('ix_alertas_tipo'), table_name='alertas')
    op.drop_index(op.f('ix_alertas_id'), table_name='alertas')
    op.drop_index(op.f('ix_alertas_estado'), table_name='alertas')
    op.drop_index(op.f('ix_alertas_empresa_id'), table_name='alertas')
    op.drop_table('alertas')
    op.drop_index(op.f('ix_cursos_id'), table_name='cursos')
    op.drop_index(op.f('ix_cursos_empresa_id'), table_name='cursos')
    op.drop_table('cursos')
    # ### end Alembic commands ###
