"""Fase 1: Inicializacion Arquitectura Limpia Multi-Tenant

Revision ID: f8d3f71b6754
Revises: 
Create Date: 2026-08-10 03:14:10.995283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8d3f71b6754'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('nombre_comercial', sa.String(length=200), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('color_primario', sa.String(length=7), nullable=True),
    sa.Column('color_secundario', sa.String(length=7), nullable=True),
    sa.Column('tema', sa.String(length=20), server_default='claro', nullable=False),
    sa.Column('favicon_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_activa'), 'empresas', ['activa'], unique=False)
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.create_index(op.f('ix_empresas_nombre'), 'empresas', ['nombre'], unique=False)
    op.create_index(op.f('ix_empresas_rut'), 'empresas', ['rut'], unique=True)
    op.create_table('higiene_personal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleado_nombre', sa.String(length=100), nullable=False),
    sa.Column('empleado_cargo', sa.String(length=50), nullable=True),
    sa.Column('fecha_auditoria', sa.Date(), nullable=False),
    sa.Column('hora_auditoria', sa.Time(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('auditor_nombre', sa.String(length=100), nullable=False),
    sa.Column('auditor_firma', sa.Text(), nullable=True),
    sa.Column('uñas_cortas_limpias', sa.Boolean(), nullable=True),
    sa.Column('manos_limpias', sa.Boolean(), nullable=True),
    sa.Column('sin_joyas', sa.Boolean(), nullable=True),
    sa.Column('uniforme_limpio', sa.Boolean(), nullable=True),
    sa.Column('cabello_cubierto', sa.Boolean(), nullable=True),
    sa.Column('calzado_adecuado', sa.Boolean(), nullable=True),
    sa.Column('sin_lesiones_visibles', sa.Boolean(), nullable=True),
    sa.Column('lavado_manos_correcto', sa.Boolean(), nullable=True),
    sa.Column('aprobado', sa.Boolean(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('foto_evidencia', sa.String(length=500), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_higiene_personal_empleado_nombre'), 'higiene_personal', ['empleado_nombre'], unique=False)
    op.create_index(op.f('ix_higiene_personal_empresa_id'), 'higiene_personal', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_higiene_personal_fecha_auditoria'), 'higiene_personal', ['fecha_auditoria'], unique=False)
    op.create_index(op.f('ix_higiene_personal_id'), 'higiene_personal', ['id'], unique=False)
    op.create_table('ingredientes_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.Enum('CARNES', 'VERDURAS', 'FRUTAS', 'LACTEOS', 'GRANOS', 'CONDIMENTOS', 'BEBIDAS', 'OTROS', name='categoriaingrediente'), nullable=False),
    sa.Column('unidad_medida', sa.Enum('KG', 'G', 'L', 'ML', 'UNIDAD', 'CAJA', 'BOLSA', name='unidadmedida'), nullable=False),
    sa.Column('stock_actual', sa.Float(), nullable=False),
    sa.Column('stock_minimo', sa.Float(), nullable=False),
    sa.Column('stock_maximo', sa.Float(), nullable=True),
    sa.Column('costo_unitario', sa.Float(), nullable=False),
    sa.Column('costo_promedio', sa.Float(), nullable=False),
    sa.Column('dias_alerta_vencimiento', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('ultima_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredientes_stock_empresa_id'), 'ingredientes_stock', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_ingredientes_stock_id'), 'ingredientes_stock', ['id'], unique=False)
    op.create_index(op.f('ix_ingredientes_stock_nombre'), 'ingredientes_stock', ['nombre'], unique=False)
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('contacto', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('ultima_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proveedores_empresa_id'), 'proveedores', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_proveedores_id'), 'proveedores', ['id'], unique=False)
    op.create_index(op.f('ix_proveedores_nombre'), 'proveedores', ['nombre'], unique=False)
    op.create_table('registro_temperaturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_nombre', sa.String(length=100), nullable=False),
    sa.Column('equipo_ubicacion', sa.String(length=100), nullable=True),
    sa.Column('temperatura', sa.Float(), nullable=False),
    sa.Column('temperatura_objetivo_min', sa.Float(), nullable=False),
    sa.Column('temperatura_objetivo_max', sa.Float(), nullable=False),
    sa.Column('fecha_medicion', sa.Date(), nullable=False),
    sa.Column('hora_medicion', sa.Time(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('responsable', sa.String(length=100), nullable=False),
    sa.Column('responsable_firma', sa.Text(), nullable=True),
    sa.Column('dentro_rango', sa.Boolean(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('foto_evidencia', sa.String(length=500), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registro_temperaturas_empresa_id'), 'registro_temperaturas', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_registro_temperaturas_equipo_nombre'), 'registro_temperaturas', ['equipo_nombre'], unique=False)
    op.create_index(op.f('ix_registro_temperaturas_fecha_medicion'), 'registro_temperaturas', ['fecha_medicion'], unique=False)
    op.create_index(op.f('ix_registro_temperaturas_fecha_registro'), 'registro_temperaturas', ['fecha_registro'], unique=False)
    op.create_index(op.f('ix_registro_temperaturas_id'), 'registro_temperaturas', ['id'], unique=False)
    op.create_table('sucursales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('ultima_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sucursales_activa'), 'sucursales', ['activa'], unique=False)
    op.create_index(op.f('ix_sucursales_empresa_id'), 'sucursales', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_sucursales_id'), 'sucursales', ['id'], unique=False)
    op.create_index(op.f('ix_sucursales_nombre'), 'sucursales', ['nombre'], unique=True)
    op.create_table('requerimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto', sa.String(length=200), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_estimado', sa.Float(), nullable=False),
    sa.Column('prioridad', sa.Enum('ALTA', 'MEDIA', 'BAJA', name='prioridad'), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requerimientos_empresa_id'), 'requerimientos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_requerimientos_id'), 'requerimientos', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('ADMINISTRADOR', 'ENCARGADO', 'OPERADOR', 'SUPER_ADMIN', name='rolusuario'), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('debe_cambiar_password', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('ultima_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_activo'), 'usuarios', ['activo'], unique=False)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_empresa_id'), 'usuarios', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_nombre_completo'), 'usuarios', ['nombre_completo'], unique=False)
    op.create_index(op.f('ix_usuarios_rol'), 'usuarios', ['rol'], unique=False)
    op.create_index(op.f('ix_usuarios_sucursal_id'), 'usuarios', ['sucursal_id'], unique=False)
    op.create_table('control_gastos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('SERVICIOS', 'INSUMOS_NO_ALIMENTICIOS', 'TRANSPORTE', 'MANTENIMIENTO', 'OTROS', name='tipogasto'), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha_gasto', sa.Date(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('proveedor', sa.String(length=200), nullable=True),
    sa.Column('numero_comprobante', sa.String(length=50), nullable=True),
    sa.Column('foto_comprobante', sa.String(length=500), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'APROBADO', 'RECHAZADO', name='estadoaprobacion'), nullable=True),
    sa.Column('responsable_usuario_id', sa.Integer(), nullable=True),
    sa.Column('aprobado_por_usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aprobado_por_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['responsable_usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_gastos_empresa_id'), 'control_gastos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_control_gastos_id'), 'control_gastos', ['id'], unique=False)
    op.create_index(op.f('ix_control_gastos_responsable_usuario_id'), 'control_gastos', ['responsable_usuario_id'], unique=False)
    op.create_table('lista_verificacion_diario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('APERTURA', 'CIERRE', name='tipochecklist'), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_registro', sa.Time(), nullable=False),
    sa.Column('fecha_hora_completa', sa.DateTime(), nullable=True),
    sa.Column('responsable_usuario_id', sa.Integer(), nullable=False),
    sa.Column('responsable_firma', sa.Text(), nullable=True),
    sa.Column('cocina_limpia', sa.Boolean(), nullable=True),
    sa.Column('cocina_ordenada', sa.Boolean(), nullable=True),
    sa.Column('basureros_vacios', sa.Boolean(), nullable=True),
    sa.Column('equipos_funcionando', sa.Boolean(), nullable=True),
    sa.Column('temperaturas_ok', sa.Boolean(), nullable=True),
    sa.Column('extintores_ok', sa.Boolean(), nullable=True),
    sa.Column('uniformes_limpios', sa.Boolean(), nullable=True),
    sa.Column('manos_lavadas', sa.Boolean(), nullable=True),
    sa.Column('cabello_cubierto', sa.Boolean(), nullable=True),
    sa.Column('almacen_ordenado', sa.Boolean(), nullable=True),
    sa.Column('sin_plagas', sa.Boolean(), nullable=True),
    sa.Column('fecha_vencimiento_revisada', sa.Boolean(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('foto_evidencia', sa.String(length=500), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['responsable_usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lista_verificacion_diario_empresa_id'), 'lista_verificacion_diario', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_lista_verificacion_diario_fecha'), 'lista_verificacion_diario', ['fecha'], unique=False)
    op.create_index(op.f('ix_lista_verificacion_diario_fecha_hora_completa'), 'lista_verificacion_diario', ['fecha_hora_completa'], unique=False)
    op.create_index(op.f('ix_lista_verificacion_diario_id'), 'lista_verificacion_diario', ['id'], unique=False)
    op.create_index(op.f('ix_lista_verificacion_diario_responsable_usuario_id'), 'lista_verificacion_diario', ['responsable_usuario_id'], unique=False)
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Enum('TAREA', 'ALERTA', 'MERMA_PENDIENTE', 'INCIDENCIA', name='tiponotificacion'), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_lectura', sa.DateTime(), nullable=True),
    sa.Column('entidad_relacionada', sa.String(length=50), nullable=True),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificaciones_empresa_id'), 'notificaciones', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_notificaciones_fecha_creacion'), 'notificaciones', ['fecha_creacion'], unique=False)
    op.create_index(op.f('ix_notificaciones_id'), 'notificaciones', ['id'], unique=False)
    op.create_index(op.f('ix_notificaciones_leida'), 'notificaciones', ['leida'], unique=False)
    op.create_index(op.f('ix_notificaciones_tipo'), 'notificaciones', ['tipo'], unique=False)
    op.create_index(op.f('ix_notificaciones_usuario_id'), 'notificaciones', ['usuario_id'], unique=False)
    op.create_table('registro_compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_factura', sa.String(length=50), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('fecha_compra', sa.Date(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('iva', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('foto_recibo', sa.String(length=500), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'APROBADO', 'RECHAZADO', name='estadoaprobacion'), nullable=True),
    sa.Column('creado_por_usuario_id', sa.Integer(), nullable=True),
    sa.Column('aprobado_por_usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aprobado_por_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['creado_por_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registro_compras_empresa_id'), 'registro_compras', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_registro_compras_id'), 'registro_compras', ['id'], unique=False)
    op.create_index(op.f('ix_registro_compras_numero_factura'), 'registro_compras', ['numero_factura'], unique=True)
    op.create_table('registro_mermas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('VENCIMIENTO', 'DAÑO', 'DERRAME', 'ROBO', 'OTRO', name='tipomerma'), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('valor_perdida', sa.Float(), nullable=False),
    sa.Column('fecha_merma', sa.Date(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('responsable_usuario_id', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('foto_evidencia', sa.String(length=500), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'APROBADO', 'RECHAZADO', name='estadoaprobacion'), nullable=True),
    sa.Column('aprobado_por_usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aprobado_por_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes_stock.id'], ),
    sa.ForeignKeyConstraint(['responsable_usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registro_mermas_empresa_id'), 'registro_mermas', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_registro_mermas_id'), 'registro_mermas', ['id'], unique=False)
    op.create_index(op.f('ix_registro_mermas_responsable_usuario_id'), 'registro_mermas', ['responsable_usuario_id'], unique=False)
    op.create_table('detalle_compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('costo_unitario', sa.Float(), nullable=False),
    sa.Column('costo_total', sa.Float(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('lote', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['compra_id'], ['registro_compras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes_stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalle_compras_empresa_id'), 'detalle_compras', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_detalle_compras_id'), 'detalle_compras', ['id'], unique=False)
    op.create_foreign_key(None, 'ajustes_inventario', 'usuarios', ['responsable_id'], ['id'])
    op.create_foreign_key(None, 'ajustes_inventario', 'empresas', ['empresa_id'], ['id'])
    op.create_foreign_key(None, 'ajustes_inventario', 'ingredientes_stock', ['ingrediente_id'], ['id'])
    op.create_foreign_key(None, 'alertas', 'usuarios', ['usuario_asignado_id'], ['id'])
    op.create_foreign_key(None, 'alertas', 'usuarios', ['usuario_creador_id'], ['id'])
    op.create_foreign_key(None, 'alertas', 'empresas', ['empresa_id'], ['id'])
    op.create_foreign_key(None, 'capacitaciones_usuarios', 'empresas', ['empresa_id'], ['id'])
    op.create_foreign_key(None, 'capacitaciones_usuarios', 'usuarios', ['usuario_id'], ['id'])
    op.create_foreign_key(None, 'conteos_fisicos', 'empresas', ['empresa_id'], ['id'])
    op.create_foreign_key(None, 'conteos_fisicos', 'sucursales', ['sucursal_id'], ['id'])
    op.create_foreign_key(None, 'conteos_fisicos', 'usuarios', ['responsable_id'], ['id'])
    op.create_foreign_key(None, 'cursos', 'empresas', ['empresa_id'], ['id'])
    op.create_foreign_key(None, 'ejecuciones_checklist', 'usuarios', ['usuario_id'], ['id'])
    op.create_foreign_key(None, 'ejecuciones_checklist', 'empresas', ['empresa_id'], ['id'])
    op.create_foreign_key(None, 'ejecuciones_checklist', 'lista_verificacion_diario', ['checklist_id'], ['id'])
    op.create_foreign_key(None, 'evidencias', 'usuarios', ['usuario_id'], ['id'])
    op.create_foreign_key(None, 'evidencias', 'empresas', ['empresa_id'], ['id'])
    op.create_foreign_key(None, 'incidencias', 'usuarios', ['asignado_a_id'], ['id'])
    op.create_foreign_key(None, 'incidencias', 'usuarios', ['reportado_por_id'], ['id'])
    op.create_foreign_key(None, 'incidencias', 'empresas', ['empresa_id'], ['id'])
    op.create_foreign_key(None, 'items_conteo', 'empresas', ['empresa_id'], ['id'])
    op.create_foreign_key(None, 'items_conteo', 'ingredientes_stock', ['ingrediente_id'], ['id'])
    op.create_foreign_key(None, 'plantillas_inventario', 'empresas', ['empresa_id'], ['id'])
    op.add_column('stock_sucursal', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('stock_sucursal', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_stock_sucursal_ingrediente_id'), table_name='stock_sucursal')
    op.drop_index(op.f('ix_stock_sucursal_sucursal_id'), table_name='stock_sucursal')
    op.drop_constraint(op.f('uq_empresa_sucursal_ingrediente'), 'stock_sucursal', type_='unique')
    op.create_unique_constraint('uq_stock_ingrediente_sucursal_empresa', 'stock_sucursal', ['ingrediente_id', 'sucursal_id', 'empresa_id'])
    op.create_foreign_key(None, 'stock_sucursal', 'empresas', ['empresa_id'], ['id'])
    op.create_foreign_key(None, 'stock_sucursal', 'ingredientes_stock', ['ingrediente_id'], ['id'])
    op.create_foreign_key(None, 'stock_sucursal', 'sucursales', ['sucursal_id'], ['id'])
    op.drop_column('stock_sucursal', 'stock_maximo')
    op.drop_column('stock_sucursal', 'stock_minimo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_sucursal', sa.Column('stock_minimo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('stock_sucursal', sa.Column('stock_maximo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stock_sucursal', type_='foreignkey')
    op.drop_constraint(None, 'stock_sucursal', type_='foreignkey')
    op.drop_constraint(None, 'stock_sucursal', type_='foreignkey')
    op.drop_constraint('uq_stock_ingrediente_sucursal_empresa', 'stock_sucursal', type_='unique')
    op.create_unique_constraint(op.f('uq_empresa_sucursal_ingrediente'), 'stock_sucursal', ['empresa_id', 'sucursal_id', 'ingrediente_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_stock_sucursal_sucursal_id'), 'stock_sucursal', ['sucursal_id'], unique=False)
    op.create_index(op.f('ix_stock_sucursal_ingrediente_id'), 'stock_sucursal', ['ingrediente_id'], unique=False)
    op.drop_column('stock_sucursal', 'updated_at')
    op.drop_column('stock_sucursal', 'created_at')
    op.drop_constraint(None, 'plantillas_inventario', type_='foreignkey')
    op.drop_constraint(None, 'items_conteo', type_='foreignkey')
    op.drop_constraint(None, 'items_conteo', type_='foreignkey')
    op.drop_constraint(None, 'incidencias', type_='foreignkey')
    op.drop_constraint(None, 'incidencias', type_='foreignkey')
    op.drop_constraint(None, 'incidencias', type_='foreignkey')
    op.drop_constraint(None, 'evidencias', type_='foreignkey')
    op.drop_constraint(None, 'evidencias', type_='foreignkey')
    op.drop_constraint(None, 'ejecuciones_checklist', type_='foreignkey')
    op.drop_constraint(None, 'ejecuciones_checklist', type_='foreignkey')
    op.drop_constraint(None, 'ejecuciones_checklist', type_='foreignkey')
    op.drop_constraint(None, 'cursos', type_='foreignkey')
    op.drop_constraint(None, 'conteos_fisicos', type_='foreignkey')
    op.drop_constraint(None, 'conteos_fisicos', type_='foreignkey')
    op.drop_constraint(None, 'conteos_fisicos', type_='foreignkey')
    op.drop_constraint(None, 'capacitaciones_usuarios', type_='foreignkey')
    op.drop_constraint(None, 'capacitaciones_usuarios', type_='foreignkey')
    op.drop_constraint(None, 'alertas', type_='foreignkey')
    op.drop_constraint(None, 'alertas', type_='foreignkey')
    op.drop_constraint(None, 'alertas', type_='foreignkey')
    op.drop_constraint(None, 'ajustes_inventario', type_='foreignkey')
    op.drop_constraint(None, 'ajustes_inventario', type_='foreignkey')
    op.drop_constraint(None, 'ajustes_inventario', type_='foreignkey')
    op.drop_index(op.f('ix_detalle_compras_id'), table_name='detalle_compras')
    op.drop_index(op.f('ix_detalle_compras_empresa_id'), table_name='detalle_compras')
    op.drop_table('detalle_compras')
    op.drop_index(op.f('ix_registro_mermas_responsable_usuario_id'), table_name='registro_mermas')
    op.drop_index(op.f('ix_registro_mermas_id'), table_name='registro_mermas')
    op.drop_index(op.f('ix_registro_mermas_empresa_id'), table_name='registro_mermas')
    op.drop_table('registro_mermas')
    op.drop_index(op.f('ix_registro_compras_numero_factura'), table_name='registro_compras')
    op.drop_index(op.f('ix_registro_compras_id'), table_name='registro_compras')
    op.drop_index(op.f('ix_registro_compras_empresa_id'), table_name='registro_compras')
    op.drop_table('registro_compras')
    op.drop_index(op.f('ix_notificaciones_usuario_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_tipo'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_leida'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_fecha_creacion'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_empresa_id'), table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_index(op.f('ix_lista_verificacion_diario_responsable_usuario_id'), table_name='lista_verificacion_diario')
    op.drop_index(op.f('ix_lista_verificacion_diario_id'), table_name='lista_verificacion_diario')
    op.drop_index(op.f('ix_lista_verificacion_diario_fecha_hora_completa'), table_name='lista_verificacion_diario')
    op.drop_index(op.f('ix_lista_verificacion_diario_fecha'), table_name='lista_verificacion_diario')
    op.drop_index(op.f('ix_lista_verificacion_diario_empresa_id'), table_name='lista_verificacion_diario')
    op.drop_table('lista_verificacion_diario')
    op.drop_index(op.f('ix_control_gastos_responsable_usuario_id'), table_name='control_gastos')
    op.drop_index(op.f('ix_control_gastos_id'), table_name='control_gastos')
    op.drop_index(op.f('ix_control_gastos_empresa_id'), table_name='control_gastos')
    op.drop_table('control_gastos')
    op.drop_index(op.f('ix_usuarios_sucursal_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_rol'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_nombre_completo'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_empresa_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_activo'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_requerimientos_id'), table_name='requerimientos')
    op.drop_index(op.f('ix_requerimientos_empresa_id'), table_name='requerimientos')
    op.drop_table('requerimientos')
    op.drop_index(op.f('ix_sucursales_nombre'), table_name='sucursales')
    op.drop_index(op.f('ix_sucursales_id'), table_name='sucursales')
    op.drop_index(op.f('ix_sucursales_empresa_id'), table_name='sucursales')
    op.drop_index(op.f('ix_sucursales_activa'), table_name='sucursales')
    op.drop_table('sucursales')
    op.drop_index(op.f('ix_registro_temperaturas_id'), table_name='registro_temperaturas')
    op.drop_index(op.f('ix_registro_temperaturas_fecha_registro'), table_name='registro_temperaturas')
    op.drop_index(op.f('ix_registro_temperaturas_fecha_medicion'), table_name='registro_temperaturas')
    op.drop_index(op.f('ix_registro_temperaturas_equipo_nombre'), table_name='registro_temperaturas')
    op.drop_index(op.f('ix_registro_temperaturas_empresa_id'), table_name='registro_temperaturas')
    op.drop_table('registro_temperaturas')
    op.drop_index(op.f('ix_proveedores_nombre'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_id'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_empresa_id'), table_name='proveedores')
    op.drop_table('proveedores')
    op.drop_index(op.f('ix_ingredientes_stock_nombre'), table_name='ingredientes_stock')
    op.drop_index(op.f('ix_ingredientes_stock_id'), table_name='ingredientes_stock')
    op.drop_index(op.f('ix_ingredientes_stock_empresa_id'), table_name='ingredientes_stock')
    op.drop_table('ingredientes_stock')
    op.drop_index(op.f('ix_higiene_personal_id'), table_name='higiene_personal')
    op.drop_index(op.f('ix_higiene_personal_fecha_auditoria'), table_name='higiene_personal')
    op.drop_index(op.f('ix_higiene_personal_empresa_id'), table_name='higiene_personal')
    op.drop_index(op.f('ix_higiene_personal_empleado_nombre'), table_name='higiene_personal')
    op.drop_table('higiene_personal')
    op.drop_index(op.f('ix_empresas_rut'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_nombre'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_activa'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
